### ISSUE TITLE
Any advice for adjustments to the folding parameters when increasing the number of points?

### ISSUE THREAD

**Issue by ninasinger** [AnTao97/UnsupervisedPointCloudFeatureLearning#5]
I'm trying to reconstruct 16384 points. Right now the points are looking very "artificial",  clear lines of points almost like scan lines. Any suggestions on what parameters to update?

**Comment by antao97** [comment]
I suggest using sphere as the reconstruction source and using more than three layers.

**Comment by ninasinger** [comment]
Thanks so much for the response! When you say additional layers, are you referring to an additional downsampling layer and then an additional folding operation or an additional hidden layer to the MLP which is performing the folding operation.

**Comment by antao97** [comment]
I think an additional folding layer may help. But I do not fully understand your case. I just think making the network more complex may work.
