### ISSUE TITLE
Graph layers

### ISSUE THREAD

**Issue by JohanYe** [AnTao97/UnsupervisedPointCloudFeatureLearning#6]
What is the reason for the oddly placed transposes and only applying a single non-linearity?

As far as i understand Conv1d with a kernel size of 1 is equivalent of appplying a linear layer on the transposed data (pytorch behavior aside). So why not just apply either two linear layers and transpose or transpose and then two convolutional layers?

Additionally, i'd like to ask for the reason for applying only a non-linearity to the output of what i presume is the first graph layer? While the second does not have any applied? And also what is the motivation for not applying them after the linear layers and only after the convolutional one?

https://github.com/AnTao97/UnsupervisedPointCloudReconstruction/blob/a5a2c648595f071c9eee23f5c80fcb5d7d733b79/model.py#L301-L308

**Comment by antao97** [comment]
I strictly reproduce this code from the original FoldingNet code. All these "odd" operations you mentioned exist in the original code.

**Comment by JohanYe** [comment]
Do you have a link to the original code? I was not aware that they had published it

**Comment by antao97** [comment]
http://www.merl.com/research/license#FoldingNet

**Comment by JohanYe** [comment]
Thank you very much!
